const button = "button";
const feature = "feature 2";
const fix = "fix";
const newBtn = "newBtn";
const idk = "idk";
const sim = "simulate new btn work";
const newSim = "sim a new component";
const test = "test a fix";
const fake = "this is a fix on a btn";
