name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version you want to release."
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      - name: Bump version in package.json
        run: yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      # - name: Checkout code
      #   uses: actions/checkout@v2
      #   with:
      #     ref: dev
      #     fetch-depth: 0

      - name: Update changelog
        run: yarn install && yarn unreleased

      - name: Commit package.json
        id: make-commit
        run: |
          git add ./package.json ./URELEASEDCHANGELOG.md
          git commit --message "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}
      

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        id: create-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: Release version ${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }}

          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.
            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.
                  Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.
      - name: Generate Comment String from Markdown
        id: getCommentContent
        uses: juliangruber/read-file-action@v1
        with:
          path: ./URELEASEDCHANGELOG.md

#         # - name: Remove Prettier Ignore Comment Start
#         #   uses: rishabhgupta/split-by@v1
#         #   id: splitCommentFront
#         #   with:
#         #     string: ${{ steps.getCommentContent.outputs.content }}
#         #     split-by: "--> "

#         # - name: Remove Prettier Ignore Comment End
#         #   uses: rishabhgupta/split-by@v1
#         #   id: splitCommentBack
#         #   with:
#         #     string: ${{ steps.splitCommentFront.outputs._1 }}
#         #     split-by: " <!--"

      - name: Add Comment to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.findExistingComment.outputs.comment-id == 0
        # In the event of 401 bad credentials, check PAT expiry on bot
        run: |
          git config --local user.email "matthew.magnotta@avb.net"
          git config --local user.name "MattyMags"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/mattymags/${{ github.event.repository.name }}/pull/${{ steps.create-pr.outputs.number }}/comments \
            -f body="${{ steps.splitCommentBack.outputs._0 }}"
