name: "Hotfix new release"

on:
  workflow_dispatch:
    inputs:
      verify-branch-is-master:
        type: boolean
        description: "Verify branch is nextjs-prod"
        required: true
      version:
        description: "The version you want to release."
        required: true

jobs:
  hotfix-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.verify-branch-is-master == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Initialize mandatory git config
        run: |
          git config --local user.email "avb-dev-services@avb.net"
          git config --local user.name "AVB Dev Bot"

      - name: Bump Version
        run: yarn version --new-version ${{ github.event.inputs.version }}

      - name: Push tags
        run: git push --follow-tags

      - name: Update changelog
        run: yarn install && yarn changelog

      - name: Run tagged changelog
        run: yarn install && node ./generateChangeLog.js && node ./taggedChangelog.js --tag=v${{ github.event.inputs.version }}

      - name: Generate Comment String from Markdown
        id: get-comment-content
        uses: juliangruber/read-file-action@v1
        with:
          path: ./TAGGEDCHANGELOG.md

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/mattymags/draft-release/releases \
            -f tag_name="v${{ github.event.inputs.version }}" \
           -f target_commitish='master' \
           -f name="Release - v${{ github.event.inputs.version }}" \
           -f body="${{ steps.get-comment-content.outputs.content }}" \
           -F draft=false \
           -F prerelease=false \
           -F generate_release_notes=false

      - name: Commit updated CHANGELOG
        run: |
          git add CHANGELOG.md changelog.json
          git commit -m 'chore: update - v${{ github.event.inputs.version }}'
          git push

      - name: Merge master back to dev
        run: |
          git fetch 
          git checkout dev
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          git push
