name: "Hotfix new release"

on:
  workflow_dispatch:
    inputs:
      verify-branch:
        type: boolean
        description: "Verify branch is nextjs-prod"
        required: true
      version:
        description: "The version you want to release."
        required: true

jobs:
  hotfix-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.verify-branch == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
          
      - name: Bump version in package.json
        run: yarn version --new-version ${{ github.event.inputs.version }} 
          
      - name: Push Tags
        run: git push --follow-tags

#       - name: Push to master
#         run: git push origin master

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/mattymags/draft-release/releases \
            -f tag_name=${{ github.event.inputs.version }}  \
           -f target_commitish='master' \
           -f name=${{ github.event.inputs.version }} \
           -f body='Description of the release' \
           -F draft=false \
           -F prerelease=false \
           -F generate_release_notes=true 
           
      - name: Merge master back to dev
        run: |
          git fetch 
          git checkout dev
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          git push
