name: "Update Changelog"
on:
  workflow_run:
    workflows: ["Publish new release", "Hotfix new release"]
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          
      - name: Get version and tag # in order topass to the commit message
        run: |
          version=$(node -p "require('./package.json').version")
          echo "CURRENT_VERSION=$version" >> $GITHUB_ENV

      - name: Update changelog
        run: yarn install && yarn changelog
        
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Commit updated CHANGELOG
        run: | 
          git add CHANGELOG.md
          git commit -m 'chore: update - ${{ env.CURRENT_VERSION }}'
          git push        

      - name: Merge master back to dev
        run: |
          git fetch --depth=1000
          git checkout dev
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          git push
