name: "Update Changelog"
on:
  workflow_run:
    workflows: ["Publish new release", "Hotfix new release"]
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Update changelog
        run: yarn install && yarn changelog

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge master back to dev
        run: |
          git fetch --depth=1000
          git checkout dev
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          git push
